// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"golang-gin-api/api"
	"golang-gin-api/api/controller"
	"golang-gin-api/config"
	"golang-gin-api/db"
	"golang-gin-api/repo"
	"golang-gin-api/service"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*server.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	
	tagRepository := repo.NewTagRepository(gormDB)
	tagsService := service.NewTagService(tagRepository)
	tagController := controller.NewTagController(tagsService)

	serverHTTP := server.NewServerHTTP(tagController)
	
	return serverHTTP, nil
}
